
services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  app:
    container_name: app
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped


volumes:
  pg-data: